# Generated by Django 3.2.12 on 2022-03-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_notifier', '0003_alter_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='celebrant',
            field=models.CharField(help_text='Celebrant Name', max_length=256, unique=True),
        ),
    ]
