# Generated by Django 3.2.12 on 2022-03-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_notifier', '0005_event_owner'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('celebrant',), name='unique title for each user'),
        ),
    ]
