# Generated by Django 3.2.12 on 2022-03-31 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_notifier', '0008_alter_event_slug'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='unique title for each user',
        ),
    ]
